sachen = {
        "Winterkleider": [
            "Warme Jacke",
            "Lange Hose",
            "Mütze",
            "Socken",
            "T-Shirts",
            "Longshirts"
        ],
        "Sommerbekleidung": [
            "kurze Hosen",
            "kurze Socken",
            "Bikini",
            "Badehosen"
            "Kleid",
            "Hemd",
            "Sweatshirtjacke",
            "Windjacke",
            "Sportschuhe",
            "Trekkingschuhe",
            "Wasserschuhe"
        ],
        "Skibekleidung": [
            "Ski",
            "Snowboard",
            "Skischcuhe",
            "Snowboardschuhe",
            "Skijacke",
            "Skihose",
            "Thermounterwäsche",
            "Skisocken",
            "Handschuhe",
            "Mützen und Ohrenwärmer",
            "Helm",
            "Skibrille",
            "Head",
            "Schal",
            "Warmer Pullover",
            "Winterschuhe",
            "Skimaske",
            "Sonnenbrille",
        ],
        "Strandbekleidung": [
            "Schnorchel",
            "Taucherbrille",
            "Flossen",
            "Badekappe",
            "Taucherbrille",
            "Taucherbrevet",
            "Strandtuch",
            "Wasserspielzeug",
            "Sonnencreme",
            "Skimaske",
            "Adiletten",
            "FlipFlops",
        ],
        "Reisedokumente": [
            "ID",
            "Gültiger Reispass",
            "Visum",
            "Bus-, Bahntickets",
            "Tickets",
            "Kopien der Reisedokumente"
        ],
        "Hygiene": [
            "Necessaire",
            "Zahnbürste und Zahnpasta"
            "Kamm",
            "Shampoo",
            "Haarspray",
            "Deo",
            "Parfüm",
            "Gesichtscreme",
            "Rasierer",
            "Taschentücher",
            "Fön",
            "Kontaktlinsen",
            "Wattestäbchen",
            "Sonnenbrille",
            "Schmuck"
        ],
        "Finanzen": [
            "Kreditkarte",
            "Bankkarte",
            "Bargeld der Auslandswährung",
            "Zugangsdaten für Onkinebanking"
        ],
        "Handy": [
            "Notfallnummer",
            "Reise-Apps",
            "Offline Karten",
            "Ladegerät",
            "Ladekbel",
            "Adapter fürs Ausland",
            "Powerbank",
            "Kopfhörer",
            "Schutzhülle"
        ],
        "Unterhaltung": [
            "Lektüre",
            "Reiseführer",
            "Stift",
            "Kamera",
            "Laptop",
            "E-Reader",
            "Spiele",
            "Filme",
            "Fernglas"
        ]
    }